  // File generated by FlutterFire CLI.
  // ignore_for_file: type=lint
  import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
  import 'package:flutter/foundation.dart'
      show defaultTargetPlatform, kIsWeb, TargetPlatform;

  /// Default [FirebaseOptions] for use with your Firebase apps.
  ///
  /// Example:
  /// ```dart
  /// import 'firebase_options.dart';
  /// // ...
  // / await Firebase.initializeApp(
  // /   options: DefaultFirebaseOptions.currentPlatform,
  // / );
  /// ```
  class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        return web;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          return macos;
        case TargetPlatform.windows:
          return windows;
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

    static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyD6r82BusJ3yUw6UxtU90g5iNmGNgpzZsc',
      appId: '1:799840218005:web:6896ecd70a314bc6cd249c',
      messagingSenderId: '799840218005',
      projectId: 'uniguide-cambodia',
      authDomain: 'uniguide-cambodia.firebaseapp.com',
      storageBucket: 'uniguide-cambodia.firebasestorage.app',
      measurementId: 'G-Q0KS15X2DV',
    );

    static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyBXOc_GchWNRKgQvUkNIM2sjTIy6kTVyDQ',
      appId: '1:799840218005:android:abb3327a7603b0b0cd249c',
      messagingSenderId: '799840218005',
      projectId: 'uniguide-cambodia',
      storageBucket: 'uniguide-cambodia.firebasestorage.app',
    );

    static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBAaOQPV7QhPDJaWrnSQmxJaA-HbIEYPUE',
      appId: '1:799840218005:ios:a400521d45266373cd249c',
      messagingSenderId: '799840218005',
      projectId: 'uniguide-cambodia',
      storageBucket: 'uniguide-cambodia.firebasestorage.app',
      iosBundleId: 'com.example.uniguideCambodia',
    );

    static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyBAaOQPV7QhPDJaWrnSQmxJaA-HbIEYPUE',
      appId: '1:799840218005:ios:a400521d45266373cd249c',
      messagingSenderId: '799840218005',
      projectId: 'uniguide-cambodia',
      storageBucket: 'uniguide-cambodia.firebasestorage.app',
      iosBundleId: 'com.example.uniguideCambodia',
    );

    static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyD6r82BusJ3yUw6UxtU90g5iNmGNgpzZsc',
      appId: '1:799840218005:web:16262fd1e44e7db1cd249c',
      messagingSenderId: '799840218005',
      projectId: 'uniguide-cambodia',
      authDomain: 'uniguide-cambodia.firebaseapp.com',
      storageBucket: 'uniguide-cambodia.firebasestorage.app',
      measurementId: 'G-PRWX0RV89T',
    );
  }
